version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.0.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install backend dependencies
          command: npm run install:api
      - run:
          name: Install frontend dependencies
          command: npm run install:frontend
      - run:
          name: Build backend
          command: npm run build:api
      - run:
          name: Build frontend
          command: npm run build:frontend
      - run:
          name: Deploy frontend
          command: npm run deploy:frontend
      - run:
          name: Deploy backend
          command: eb deploy Udagramapp-env
