version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.0.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install backend dependencies
          command: npm run install:api
      - run:
          name: Build backend
          command: npm run build:api
      - run:
          name: Initialize the Elastic Beanstalk
          command: eb init udagram-app -p node.js-16 -r $AWS_DEFAULT_REGION
      - run:
          name: Passing environment variables
          command: eb setenv $TEST
      - run:
          command: cat ./.elasticbeanstalk/config.yml
      - run:
          name: Deploy backend
          command: |
            eb deploy Udagramapp-env
      - run:
          name: Install frontend dependencies
          command: npm run install:frontend
      - run:
          name: Build frontend
          command: npm run build:frontend
      - run:
          name: Deploy frontend
          command: npm run deploy:frontend
